### ISSUE TITLE
Different size of sam by minimap2 and rustybam paf-to-sam

### ISSUE THREAD

**Issue by baozg** [mrvollger/rustybam#15]
Hi, @mrvollger 

Thanks for this cool tool. But `paf-to-sam` seems not worked as the aligner did (eg. `minimap2`).

 - The exact command that produced the error along with the error message.

I use the dataset from wfmash data, chrI with SK1 and SGD_ref
```bash
# genomes form wfmash  https://github.com/waveygang/wfmash/blob/main/data/scerevisiae8.fa.gz

samtools faidx scerevisiae8.fa.gz SGDref#1#chrI |sed "s//SGDref#1#/g" > sgd_ref.fa
samtools faidx scerevisiae8.fa.gz SK1#1#chrI |sed "s//SK1#1#/g" > sk1.fa
samtools faidx sk1.fa

# PAF
minimap2 -x asm5 -c --eqx sgd_ref.fa sk1.fa > mm2.paf
# sam
minimap2 -ax asm5 --eqx sgd_ref.fa sk1.fa > mm2.sam
```
<img width="764" alt="image" src="https://github.com/mrvollger/rustybam/assets/20680150/36f2c379-62c9-486a-987b-7ddc32d5ab4d">

```bash
# rustybam
rustybam paf-to-sam -f sk1.fa mm2.paf > mm2_rustybam.sam
grep -v "^@" mm2_rustybam.sam|awk '{print length($10)}'
```
<img width="644" alt="image" src="https://github.com/mrvollger/rustybam/assets/20680150/949daadc-ba9d-46d1-86be-e756964f0f87">

The every line of sequence from the rustybam is the query genome size, but this should be aligned sequence, right?
<img width="582" alt="image" src="https://github.com/mrvollger/rustybam/assets/20680150/933e0db7-a268-45c4-af6b-b6d4636d60d3">

 - A minimal example that reproduces the error including example input files uploaded to github.
 https://github.com/waveygang/wfmash/blob/main/data/scerevisiae8.fa.gz

 - Version of rustybam [e.g. v0.1.19]
 0.1.31
 - OS: [e.g. MacOS, unix, linux]
Ubuntu 20, installed by bioconda

**Comment by mrvollger** [comment]
The PAF format has no flag for primary vs. secondary alignments, so Rustybam assumes all alignments are primary, which is noted in the help message of the tool. This means that all the alignments that are hard-clipped in mm2 because they are secondary or supplemental are soft-clipped in the `tb` conversion. Therefore, the whole query sequence is maintained.

But if you look at the stats of these alignments, you will find they are identical. 
```
diff <(rb stats mm2_rustybam.sam) <(rb stats mm2.sam)
```
(returns nothing)

So it is just a soft vs hardclipping difference. 

Please re-poen if you have questions or find other issues.

**Comment by baozg** [comment]
Thanks for the quick check. But I think that's also the major difference between reads and assembly sam (maybe sam is not suited for assembly). My main motivation for using sam / bam for WGA is visualization interactively in IGV with multiple bam and annotation (If only one, SafFire would be perfect). Usually, we cannot have end-to-end chromosome alignment, especially for divergent species. So the hard clipped is the only way to present these aligned blocks, otherwise the sequence would be too big.

**Comment by mrvollger** [comment]
It is relatively simple to convert soft to hard clips (e.g. https://fulcrumgenomics.github.io/fgbio/tools/latest/ClipBam.html) and impossible to do the other way around, so I won't be changing the `rb` output due to file size concern from soft-clipping. 

> So the hard clipped is the only way to present these aligned blocks, otherwise the sequence would be too big.
I do agree that it is sometimes a (much) larger file, but this ^ isn't really true, IGV can load bams that are >1TB of data without issue. Unless I am misunderstanding your comment here?

**Comment by baozg** [comment]
I see a very large sam from `rustybam` from A.thaliana with two accessions alignment, maybe because of the centromere alignment fragment. It could produce 42G sam and is very slow for converting. The bam I also used for SVs calling to fed into like `svim-asm` tool. Due to the abnormal size, I haven't tested them.
