### ISSUE TITLE
how to gain the mapping identity

### ISSUE THREAD

**Issue by zhoudreames** [mrvollger/rustybam#2]
when i run rustybam 1.bam >1.bed ,this result show in blow,but there are no identity information in this result,how to gain it ? thanks
![image](https://user-images.githubusercontent.com/54714639/125376299-48860980-e3bd-11eb-9a1a-790243a44cc1.png)

**Comment by mrvollger** [comment]
I think your cigar string is constructed with the match (`M`) operator instead of the equal (`=`) and mismatch (`X`) operators. Since `M` can be either a match or a mismatch in the alignment the program assumes a mismatch when calculating identity. Additional the program should have emitted warning messages to this affect while running.

To get a compliant cigar string with minimap2 for example you need to add the `--eqx` flag. For example:
``` minimap2 -ax asm20 --eqx input.fa reads.fa | samtools view -b - > 1.bam```

**Comment by zhoudreames** [comment]
> I think your cigar string is constructed with the match (`M`) operator instead of the equal (`=`) and mismatch (`X`) operators. Since `M` can be either a match or a mismatch in the alignment the program assumes a mismatch when calculating identity. The program should have emitted warning messages to this affect while running.
> 
> To get a compliant cigar string with minimap2 for example you need to add the `--eqx` flag. For example:
> ` minimap2 -ax asm20 --eqx input.fa reads.fa | samtools view -b - > 1.bam`

thanks~
